FROM node:14-alpine as build

WORKDIR /app

COPY ./frontend/react ./
COPY ./.env ./

RUN npm install

RUN npm i seedrandom --save

RUN npm run build

FROM nginx:latest

COPY --from=build /app/build /home/build

COPY ./frontend/nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./frontend/nginx/sites-enabled /etc/nginx/sites-enabled/

RUN rm -rf /etc/nginx/conf.d/

COPY ./frontend/nginx/conf.d/ /etc/nginx/conf.d/

RUN chmod -R 777 /home/build

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]