FROM nginx:latest

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./nginx/sites-enabled /etc/nginx/sites-enabled/

RUN rm -rf /etc/nginx/conf.d/
COPY ./nginx/conf.d/ /etc/nginx/conf.d/

COPY ./build /home/build/

RUN chmod -R 777 /home/build

EXPOSE 80